### ISSUE TITLE
Payment gateway information is not saved

### ISSUE THREAD

**Issue by sipak** [Attendize/Attendize#155]
I am trying to use Coinbase or Stripe as payment gateway. When I enter API key, secret and account ID and click Save account details, I get message that everything was save. Unfortunately when I get back to Account setting, all the fields are empty again.

**Comment by bretto36** [comment]
Can i just ask, are you clicking the "Save Payment Details" button or "Save Account Details" Button. You need to click the Save button that appears on the tab you are using. It should say Save Payment Details. 

I have tested on the latest version and this works for me for both Stripe and Coinbase

**Comment by sipak** [comment]
Yes, I click Save Payment Details button. Then confirmation message appears but when I get back to the Account setting, payment details are empty,

**Comment by sipak** [comment]
Details "saved"
![01](https://cloud.githubusercontent.com/assets/4264782/16609817/443f0ba8-4357-11e6-9114-0ded46c3a650.JPG)
But not really
![02](https://cloud.githubusercontent.com/assets/4264782/16609816/443c8bbc-4357-11e6-8d52-46cd282d60f8.JPG)

**Comment by daveearley** [comment]
If you have access to your DB could you look at the **account_payment_gateways** table and see if there are any rows?

And if so, what's in the **config** field of any of the rows?

Cheers

**Comment by sipak** [comment]
This is what is saved in DB for organizer where I tried PayPal gateway (above)
{"apiKey":"aaa","publishableKey":"aa"} 
{"apiKey":"","secret":"","accountId":""}

**Comment by bretto36** [comment]
Is the account id column getting the correct value? Match it up with the accounts table and check.

**Comment by sipak** [comment]
Yes, account id matches the id from accounts table.

**Comment by daveearley** [comment]
This is an odd one, if the JSON is being saved to the DB it should be working. Are there any errors in the log file in **Storage/logs**?

I assume it's something to do with json_decode failing.

**Comment by hubiktomas** [comment]
Hi, I am the admin for sipak's page so I have the access to the DB, logs etc. The storage/logs contains only gitignore file, nothing else.

There are some entries in the webserver error log - attached. It does not seem that the errors are related to this issue.

[log.txt](https://github.com/Attendize/Attendize/files/355572/log.txt)

**Comment by chill117** [comment]
@hubiktomas What version of attendize are you guys running?

**Comment by hubiktomas** [comment]
Head of master branch. Pulled right now, problem still persists.

**Comment by daveearley** [comment]
Have you renamed or removed anything in the **config/attendize.php** file?

**Comment by hubiktomas** [comment]
No, I have not. The only editted/removed file is the bootstrap/cache/compiled.php because of issue #141 and .env

**Comment by chill117** [comment]
It's taking a long time for me to get a working test instance setup.  I probably won't be able to find a fix for this until next week some time.

**Comment by chill117** [comment]
@hubiktomas @daveearley  Found the problem. The following lines:
```php
    public function getGateway($gateway_id)
    {
        return $this->gateways->where('payment_gateway_id', $gateway_id)->first();
    }
```
Should be changed to:
```php
    public function getGateway($gateway_id)
    {
        return $this->gateways->where('payment_gateway_id', (string) $gateway_id)->first();
    }
```
The reason is because the `$this->gateways` collection stored the `payment_gateway_id` field as a __string__ internally. But the `$gateway_id` variable is an integer here. I think this should be fixed by properly defining the column types on the `AccountPaymentGateway` model.

**Comment by hubiktomas** [comment]
@chill117 Thank you very much. This fix works!

**Comment by daveearley** [comment]
Thanks for this @chill117,  however when I make the change you posted I'm now unable to save the payment data. Based on that I assume the issue is related to the database being used. 

@hubiktomas what database are you using?

Does using the following code work also:

```
public function getGateway($gateway_id)
    {
        return $this->gateways->where('payment_gateway_id', (int) $gateway_id)->first();
    }
```

Cheers!

**Comment by hubiktomas** [comment]
@daveearley I am using MySQL 5.5 with UTF-8 charset. The structure was created using the installer based on instructions in the documentation - manual install from the repository.

Regarding the integer cast - no, using this change the info is not loaded.

Thanks.

**Comment by chill117** [comment]
> Thanks for this @chill117, however when I make the change you posted I'm now unable to save the payment data. Based on that I assume the issue is related to the database being used.

@daveearley I don't understand. Does Attendize not support the use of MySQL? If it does, then the issue needs to be solved by properly defining data types on the data models used in Attendize so that bugs like this don't happen. I suspect there are more places in the code base with this issue. Solving it at a low level (ie. within the model definitions) would be best in my opinion, because it would simplify usage of the data models throughout the rest of the code base.

**Comment by daveearley** [comment]
Casting the data types would solve the issue, but I was simply curious why this was causing an issue in this particular instance. Laravel/Eloquent are usually extremely lenient when it comes to data types, so not casting the types usually doesn't cause any problems.

**Comment by pajasevi** [comment]
❤️  you guys are awesome ❤️

**Comment by ethode** [comment]
This should be closed, no?  It's marked as open
